CREATE TABLE TARIFFS (
TARIFF_ID NUMBER (1) PRIMARY KEY,
NAME VARCHAR2 (30),
MONTHLY_FEE NUMBER (4),
DATA_LIMIT NUMBER (6),
MINUTE_LIMIT NUMBER (5),
SMS_LIMIT NUMBER (5)
);

CREATE TABLE CUSTOMERS (
CUSTOMER_ID NUMBER (5) PRIMARY KEY,
NAME VARCHAR2(20),
CITY VARCHAR2 (20),
SIGNUP_DATE DATE,
TARIFF_ID NUMBER(1),
CONSTRAINT FK_TARIFF_ID FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS(TARIFF_ID)
);

CREATE TABLE MONTHLY_STATS (
ID NUMBER (5) PRIMARY KEY,
CUSTOMER_ID NUMBER (5),
DATA_USAGE NUMBER (8,2),
MINUTE_USAGE NUMBER (4),
SMS_USAGE NUMBER (5),
PAYMENT_STATUS VARCHAR2 (10),
CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);